name: ssyrial
description: "SSAFY 신한은행 해커톤 프로젝트 클라이언트"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.0-26.0.dev

dependencies:
  flutter:
    sdk: flutter

  # 상태 관리 (State Management)
  flutter_bloc: ^8.1.6 # BLoC 패턴을 사용한 상태 관리

  # 의존성 주입 (Dependency Injection)
  get_it: ^7.2.0 # 의존성 주입을 위한 패키지

  # REST API 통신 (API Communication)
  dio: ^5.1.0 # HTTP 클라이언트로 사용 (API 호출용)

  # 데이터 직렬화 (Data Serialization)
  json_annotation: ^4.8.0 # JSON을 Dart 객체로 변환하기 위한 어노테이션 패키지
  freezed_annotation: ^2.3.2 # Freezed 패키지와 함께 사용되는 어노테이션 (불변 클래스 생성)

  # 네비게이션 관리 (Navigation Management)
  go_router: ^14.2.3 # Flutter 앱 내의 간단한 라우팅 및 네비게이션 관리

  # UI 및 디자인 (UI & Design)
  google_fonts: ^6.2.1 # 구글 폰트를 쉽게 적용하기 위한 패키지
  cupertino_icons: ^1.0.8 # iOS 스타일의 아이콘을 제공하는 패키지
  flutter_spinkit: ^5.1.0 # 로딩 애니메이션 위젯 제공
  flutter_svg: ^2.0.10+1 # SVG 이미지 렌더링을 위한 패키지

  # 폼 검증 (Form Validation)
  formz: ^0.7.0 # 폼 입력의 유효성 검사를 쉽게 처리할 수 있는 유틸리티

  # 로컬 저장소 (Local Storage)
  hive: ^2.2.3 # Key-value 데이터베이스, 로컬 저장소로 사용
  hive_flutter: ^1.1.0 # Flutter와 함께 Hive 사용 시 필요한 패키지

dev_dependencies:
  flutter_test:
    sdk: flutter

  # 코드 린팅 (Code Linting)
  flutter_lints: ^4.0.0 # 린트를 통해 코드 품질 유지

  # 코드 생성 도구 (Code Generation Tools)
  build_runner: ^2.4.0 # 코드 생성기 (예: json_serializable, Freezed) 실행을 위한 패키지
  freezed: ^2.3.2 # Freezed 코드를 생성하기 위한 패키지
  json_serializable: ^6.5.4 # JSON 직렬화를 위한 코드 생성 패키지

  # 테스트 관련 유틸리티 (Testing Utilities)
  mockito: ^5.3.2 # 유닛 테스트에서 의존성 목킹용
  bloc_test: ^9.1.0 # BLoC 상태 관리 테스트를 위한 패키지

flutter:

  # Material Design 아이콘 사용 (Enable Material Design icons)
  uses-material-design: true

  # 애셋 설정 (Assets Configuration)
  assets:
    - assets/images/

  # 커스텀 폰트 설정 (Custom Fonts Configuration)
  # fonts:
  #   - family: CustomFontFamily
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
  #         weight: 700